name: APK Automation

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6 AM UTC

jobs:
  build-and-notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests zipfile
      - name: Run APK automation script
        run: python apk_automation.py
